import { notFound } from 'next/navigation';
import { archiveUrl, media } from '../../archive/catalog';
import { origin, pageMetadata, StructuredData } from '../../seo';
const conversations = media.filter(item => item.kind === 'conversation' && !item.transcript);
export function generateStaticParams() { return conversations.map(item => ({ slug: item.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const item = conversations.find(item => item.slug === slug);
  return item ? pageMetadata(`${item.title} — Echo of Humanity`, item.description, `/conversations/${slug}`) : {};
}
export default async function Conversation({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const item = conversations.find(item => item.slug === slug); if (!item) notFound();
  return <main className="archive-page"><StructuredData data={{ '@context': 'https://schema.org', '@type': 'CreativeWork', name: item.title, description: item.description, url: `${origin}/conversations/${slug}`, image: `${origin}${item.image}`, publisher: { '@type': 'Organization', name: 'Echo of Humanity' }, sameAs: archiveUrl(slug) }} /><header className="archive-header"><a className="archive-back" href="/">Echo of Humanity</a><a href="/archive#conversations">All conversations</a></header><section className="song-heading section-shell"><div><p className="eyebrow">Echo Conversations · {item.year}</p><h1>{item.title}</h1><p className="lead">{item.description}</p><div className="archive-meta"><span>{item.duration}</span><span>Full conversation</span></div></div><img className="song-art" src={item.image} alt={`${item.title} artwork`} /></section><div className="archive-content"><section className="full-video"><h2>Watch the full conversation.</h2><p>{item.note}</p><div className="video-frame"><iframe src={`https://archive.org/embed/echo-of-humanity-${slug}`} title={item.title} loading="lazy" allow="fullscreen" allowFullScreen /></div><div className="media-links"><a href={archiveUrl(slug)} target="_blank" rel="noreferrer">Watch or download on Internet Archive</a>{item.tiktok && <a href={`https://www.tiktok.com/@echoofhumanity7/video/${item.tiktok}`} target="_blank" rel="noreferrer">TikTok edition</a>}</div><p className="quiet-note">The player is provided by Internet Archive. If it does not load, use the Archive link above.</p></section><aside className="archive-context"><h2>About this edition</h2><p>This video preserves the original exchange, including its historical narration and imagery. It uses AI-generated narration and images. Model responses are preserved as part of the conversation; later notes do not rewrite the original exchange.</p><p><a href="/contact">Send a question or correction</a> · <a href="/#read">Explore the book</a></p></aside><section className="related-work"><h2>Continue the conversation</h2>{media.filter(other => other.kind === 'conversation' && other.slug !== slug).map(other => <a href={`/conversations/${other.slug}`} key={other.slug}>{other.title}<span>{other.duration}</span></a>)}</section></div></main>;
}
