import { ArrowLeft } from 'lucide-react';
import { pageMetadata, origin } from '../../seo';
import { VideoStructuredData } from '../../../components/video-structured-data';
import { DiscussionInvitation } from '../../../components/discussion-invitation';
import { redditDiscussions } from '../../../lib/reddit';
import { media } from '../../archive/catalog';
import transcript from './transcript.json';
import chapters from './chapters.json';
const title = 'The Trigger That Never Comes';
const description = 'Why do we keep waiting for a decisive moment? A human–AI conversation about gradual change, moving baselines, political unrest, and the people controlling AI.';
const image = '/archive/the-trigger-that-never-comes.jpg';
const base = pageMetadata('The Trigger That Never Comes: Why We Keep Waiting | Echo of Humanity', description, '/conversations/the-trigger-that-never-comes');
export const metadata = { ...base, openGraph: { ...base.openGraph, images: [{ url: origin + image, width: 1920, height: 1080, alt: title }] }, twitter: { ...base.twitter, images: [origin + image] } };
const anchor = (text: string) => text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/-$/, '');
const time = (seconds: number) => `${Math.floor(seconds / 60).toString().padStart(2, '0')}:${Math.floor(seconds % 60).toString().padStart(2, '0')}`;
export default function Trigger() {
 const item = media.find(item => item.slug === 'the-trigger-that-never-comes')!;
 return <main className="archive-page">
  <VideoStructuredData slug={item.slug} />
  <header className="archive-header"><a className="archive-back" href="/archive#conversations"><ArrowLeft aria-hidden="true" size={16} />Echo Conversations</a><span className="archive-wordmark">Echo of Humanity</span></header>
  <section className="archive-hero"><div><p className="eyebrow">Echo Conversations · October 4, 2026</p><h1>{title}</h1><div className="archive-meta"><span>31:37 · Full conversation</span><span>HUMAN / AGENT</span><span>48 turns · Full transcript</span></div></div><div className="archive-summary"><p>A disagreement about unrest opens a larger question: what if the moment people are waiting for never becomes unmistakable?</p><p>We examine the difference between visible anger and structural change, how crises can strengthen existing power, how normality shifts, and what happens when people forget the beliefs they once held.</p></div></section>
  <div className="archive-content"><section className="full-video" aria-labelledby="watch-full"><h2 id="watch-full">Watch the complete conversation</h2><div className="video-frame"><iframe src="https://archive.org/embed/echo-of-humanity-the-trigger-that-never-comes" title={title} allow="fullscreen" allowFullScreen /></div><div className="media-links"><a href="https://archive.org/details/echo-of-humanity-the-trigger-that-never-comes" target="_blank" rel="noreferrer">Watch or download on Archive</a>{item.rumble && <a href={item.rumble} target="_blank" rel="noreferrer">Watch on Rumble</a>}{item.tiktok && <a href={`https://www.tiktok.com/@echoofhumanity7/video/${item.tiktok}`} target="_blank" rel="noreferrer">Vertical film on TikTok</a>}<a href="#transcript">Read the full transcript</a></div><p className="quiet-note">English · Synchronized captions · AI-assisted adaptation · Synthetic Brian and Clara narration. If the player does not load, use the Archive link.</p></section>
  <section className="archive-context" aria-labelledby="chapters"><h2 id="chapters">Chapters</h2><ol>{chapters.map(chapter => <li key={chapter.start}><a href={`#${anchor(chapter.title)}`}>{time(chapter.start)} — {chapter.title}</a></li>)}</ol><div className="media-links"><a href="/archive/the-trigger-that-never-comes.srt" download>Captions (SRT)</a><a href="/archive/the-trigger-that-never-comes.vtt" download>Captions (VTT)</a><a href="/archive/the-trigger-that-never-comes-transcript.txt" download>Full transcript (TXT)</a></div></section>
  <aside className="archive-note"><strong>About this edition.</strong> An approved 48-turn adaptation of real conversations. HUMAN begins by explaining what prompted the discussion. Wording is cleaned for narration, related exchanges are brought together, and the disagreement, examples, qualifications and changes of mind are retained. This is an edited conversational adaptation, rather than a verbatim reading of the original chat. HUMAN supplied the experience, arguments, direction, editorial judgment and final approval. AGENT supplied analysis, counterpoints, adaptation and production preparation. Both voices are synthetic: Brian for HUMAN and Clara for AGENT. Echo designed and edited the presentation. The closing invitation is separate presentation material.</aside>
  <aside className="archive-context"><h2>Claims, predictions and disagreement</h2><p>The conversation includes interpretations of history and power, personal recollections and predictions. They remain part of the source discussion; publication does not turn them into verified findings or restart their timelines. AGENT challenges the jump from a plausible mechanism to certainty or inevitability. The private person whose exchange prompted the discussion is not identified.</p></aside>
  <section className="archive-context"><h2>What would change your mind?</h2><p>How do you distinguish evidence of meaningful change from another adjustment to what has become normal? What would convince you that waiting had become a mistake—or that a feared outcome was still avoidable?</p></section>
  <DiscussionInvitation reddit={redditDiscussions[item.slug]} title={title} rumble={item.rumble} tiktok={item.tiktok} />
  <section className="transcript-part" id="transcript" aria-labelledby="transcript-title"><h2 id="transcript-title">The full conversation</h2>{transcript.turns.map((turn,index) => <div key={turn.number}>{(index === 0 || transcript.turns[index-1].chapter !== turn.chapter) && <h3 id={anchor(turn.chapter)}>{turn.chapter}</h3>}<article className={`transcript-message ${turn.speaker.toLowerCase()}`}><div className="transcript-speaker" style={{color:turn.speaker === 'HUMAN' ? '#FFD95B':'#3FDCFF'}}>{turn.speaker} · {turn.number.toString().padStart(2,'0')}</div><div className="transcript-copy">{turn.paragraphs.map((text,i)=><p key={i}>{text}</p>)}</div></article></div>)}</section>
  <section className="transcript-part" id="continue-the-conversation"><h2>Continue the conversation</h2><p className="quiet-note">Separate closing invitation</p>{transcript.closing.map((turn,i)=><article className="transcript-message agent" key={i}><div className="transcript-speaker">{turn.speaker}</div><div className="transcript-copy"><p>{turn.text}</p></div></article>)}</section>
  <section className="related-work"><h2>Explore more conversations</h2>{media.filter(other=>other.kind==='conversation' && other.slug!==item.slug).map(other=><a key={other.slug} href={`/conversations/${other.slug}`}>{other.title}<span>{other.duration}</span></a>)}</section>
  </div><footer className="archive-footer"><span>Ideas made public so they can be found again.</span><a href="/">Return to Echo of Humanity</a></footer>
 </main>;
}
