import { ArrowUpRight, BookOpen, Heart } from 'lucide-react';
import { pageMetadata } from '../seo';
export const metadata = pageMetadata('Support & transparency — Echo of Humanity', 'Choose how to support Echo: direct support, the book, and a clear account of fees, costs, and what reaches the work.', '/support');

export default function Support() {
  return <main className="archive-page">
    <header className="archive-header"><a className="archive-back" href="/">Echo of Humanity</a><a href="/archive">Explore the work</a></header>
    <article className="support-page section-shell">
      <div className="support-intro"><p className="eyebrow">Optional support · Clear choices</p><h1>Know what your support makes possible.</h1><p className="lead">Help us keep making conversations, music, and books. Choose the way that makes sense for you, with a clear explanation of the costs and what reaches the work.</p><p>Listening, reading, asking questions, commenting, and sharing a work that matters to you are welcome forms of support too.</p></div>
      <div className="support-options">
        <section className="support-option"><Heart aria-hidden="true" /><p className="eyebrow">Available now</p><h2>Give directly</h2><p>Make an optional contribution through Buy Me a Coffee. The checkout is on our shared support page, named “Our Projects.” This page supports more than one project; contributions are not automatically earmarked to Echo.</p><a className="primary-link" href="https://buymeacoffee.com/capto50z" target="_blank" rel="noreferrer">Support Echo <ArrowUpRight size={16} aria-hidden="true" /></a><dl><div><dt>You choose the amount</dt><dd>The checkout shows your total before payment.</dd></div><div><dt>What reaches us</dt><dd>Your contribution less applicable platform, processing, and payout fees. There is no product to manufacture or ship.</dd></div></dl><p className="quiet-note">This is support for creative work, not a charitable tax-deductible donation.</p></section>
        <section className="support-option"><BookOpen aria-hidden="true" /><p className="eyebrow">Available now · Kindle edition</p><h2>Buy the book</h2><p><em>The Echo of Humanity</em> brings the founding conversation into a book you can keep and return to.</p><a className="primary-link" href="https://www.amazon.com/dp/B0HJHPY4J7" target="_blank" rel="noreferrer">View the book on Amazon <ArrowUpRight size={16} aria-hidden="true" /></a><dl><div><dt>Current price</dt><dd>Shown on Amazon for your country and currency.</dd></div><div><dt>What reaches us</dt><dd>The author royalty after Amazon’s applicable deductions. A verified per-sale amount is not yet available here, so we are not claiming a dollar amount or percentage.</dd></div></dl><p className="quiet-note">The free web reading edition is planned after the current Amazon exclusivity term ends.</p></section>
      </div>
      <section className="support-transparency"><p className="eyebrow">Published fee illustration · checked September 24, 2026</p><h2>A $10 contribution is not $10 received.</h2><p>Buy Me a Coffee lists a 5% platform fee, standard processing of 2.9% + $0.30, and a 0.5% payout fee. International payments and subscriptions can carry additional charges.</p><div className="support-example"><p><strong>Illustration:</strong> on a one-time $10 US payment, if we cover all those standard fees, roughly <strong>$8.86</strong> remains before taxes and project expenses. This is an estimate from the published rates, not a receipt or a verified account-specific settlement.</p></div><p>Who covers card fees, the payment method, location, and payout calculation can change the result. Check the checkout total and <a href="https://help.buymeacoffee.com/en/articles/8105744-how-to-calculate-charges-on-your-payment" target="_blank" rel="noreferrer">Buy Me a Coffee’s current fee explanation</a>.</p></section>
      <section className="support-transparency"><p className="eyebrow">Future options</p><h2>Merchandise, when it is ready.</h2><p>There is no Echo merchandise available to buy yet. If we add shirts, printed books, or other products, each listing here will explain the price, direct costs, fees, and estimated amount left for the work.</p><p>You should be able to decide whether you want the product as well as the support it provides. A higher purchase price does not necessarily leave more for Echo than a smaller direct contribution.</p></section>
      <section className="support-transparency"><p className="eyebrow">Our transparency standard</p><h2>Show the numbers. Label the unknowns.</h2><ul><li>Show the customer price and whether shipping and sales tax are additional.</li><li>Show production, fulfillment, platform, and payment costs where they apply.</li><li>Show the estimated amount remaining for the work, with a date and the assumptions behind it.</li><li>Distinguish that amount from profit: income taxes, tools, time, and other project expenses may still have to be covered.</li><li>Mark estimates and unverified amounts clearly, and update them when costs or prices change.</li></ul><p>Have a question about an option or a number? <a href="mailto:echoofhumanity50@gmail.com?subject=Echo%20support%20transparency">Email us</a>. You can always <a href="/archive">return to the free conversations and music</a>.</p></section>
    </article>
  </main>;
}
